// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://heysdwwclyriczrjevjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhleXNkd3djbHlyaWN6cmpldmp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwODYyMjksImV4cCI6MjA2ODY2MjIyOX0.dcQFfhLbFD63Ho6seW3gKHGrQvCA7YRuaTO1h0D7xlE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});